In [1]:
%matplotlib inline
import pandas as pd
fname = "../data/SS_DATA.txt"

In [67]:
df = pd.read_csv(fname, sep='\t', header=0)
df

,org,fund,program,object,col,mut,mud,data,proj,grnt
0,ATAT000001,100000,0,524,V55_TOTAL,B,0,5.24e+03,0,LALS000000
1,ATAT000001,100000,0,651532,CY_REVBUD,B,0,1.49e+05,3MFTS2AT01,LALS000000
2,ATAT000001,100000,0,642233,PY1_ACTUAL,B,0,3.51e+05,7AT2WA0001,LALS000000
3,ATAT000001,100000,0,BUEXP,V55_TOTAL,B,AT_07,2.28e+05,3MFFA2AT01,LALS000000
4,ATAT000001,100000,0,521100,PY1_ACTUAL,B,0,2.76e+03,0,LALS000000
5,ATAT000001,100000,0,651602,CY_REVBUD,B,0,6.32e+04,3MFRM2AT01,LALS000000
6,ATAT000001,100000,0,EMS,V55_TOTAL,B,AT_05,7.50e+04,0,LALS000000
7,ATAT000001,100000,0,629011,PY1_ACTUAL,B,0,4.67e+05,7AT2PL0001,LALS000000
8,ATAT000001,100000,0,R,V55_TOTAL,B,0,4.84e+03,7AT2PK0001,LALS000000
9,ATAT000001,100000,0,6515,PY1_ACTUAL,B,0,3.55e+05,3MFTS2AT01,LALS000000
10,ATAT000001,100000,0,642,CY_REVBUD,B,0,2.40e+05,7AT2HC0001,LALS000000
11,ATAT000001,100000,0,65,V55_TOTAL,B,0,1.70e+05,3MFRM2AT01,LALS000000
12,ATAT000001,100000,0,6516,V55_TOTAL,B,0,1.70e+05,3MFRM2AT01,LALS000000
13,ATAT000001,100000,0,642233,CY_REVBUD,B,0,1.02e+06,7AT2ES0001,LALS000000
14,ATAT000001,100000,0,6422,V55_TOTAL,B,0,2.42e+05,7AT2HC0001,LALS000000
15,ATAT000001,100000,0,549000,V55_TOTAL,B,0,2.87e+04,0,LALS000000
16,ATAT000001,100000,0,542400,CY_REVBUD,B,0,4.11e+03,0,LALS000000
17,ATAT000001,701000,0,549,PY1_ACTUAL,B,0,-4.00e+00,0,LALS000000
18,ATAT000001,100000,0,BUEXP,PY1_ACTUAL,B,0,-1.00e+02,0,LAASCA0000
19,ATAT000001,100000,0,FTE_TOT,V55_TOTAL,B,AT_01,1.00e+00,0,LALS000000
20,ATAT000001,100000,0,651520,PY1_ACTUAL,B,0,1.55e+03,3MFTS2AT01,LALS000000
21,ATAT000001,100000,0,E,V55_TOTAL,B,AT_06,1.52e+05,0,LALS000000
22,ATAT000001,100000,0,487210,V55_TOTAL,B,AT_10,6.54e+04,0,LALS000000
23,ATAT000001,100000,0,651211,PY1_ACTUAL,B,0,1.64e+03,3MFPD2AT01,LALS000000
24,ATAT000001,100000,0,651512,CY_REVBUD,B,0,3.04e+04,3MFTS2AT01,LALS000000
25,ATAT000001,100000,0,651522,PY1_ACTUAL,B,0,8.30e+04,3MFTS2AT01,LALS000000
26,ATAT000001,100000,0,487210,V55_TOTAL,B,AT_04,0.00e+00,0,LALS000000
27,ATAT000001,100000,0,E,PY1_ACTUAL,B,0,-1.00e+02,0,LAASCA0000
28,ATAT000001,100000,0,48,V55_TOTAL,B,AT_05,7.50e+04,0,LALS000000
29,ATAT000001,100000,0,514540,V55_TOTAL,B,AT_01,5.20e+03,0,LALS000000
...,...,...,...,...,...,...,...,...,...,...
338629,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_09,0.00e+00,0,CDED000000
338630,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_08,-4.10e+04,0,CDED000000
338631,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_07,-1.12e+05,0,CDED000000
338632,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_06,0.00e+00,0,CDED000000
338633,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_05,0.00e+00,0,CDTR000000
338634,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_04,3.00e+04,0,CDED000000
338635,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_03,0.00e+00,0,CDTR000000
338636,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_03,0.00e+00,0,CDED000000
338637,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_02,0.00e+00,0,CDED000000
338638,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,ZD_01,0.00e+00,0,CDED000000
338639,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,4.25e+05,0,CDTREN0000
338640,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,1.34e+06,0,CDTRBD0000
338641,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,0.00e+00,0,CDTR000000
338642,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,1.32e+06,0,CDEDWF0000
338643,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,3.18e+05,0,CDEDLI0000
338644,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,9.34e+05,0,CDEDBD0000
338645,ZDFS000001,100000,0,BUEXP,V55_TOTAL,B,0,1.19e+06,0,CDED000000
338646,ZDFS000001,100000,0,BUEXP,PY1_ACTUAL,B,0,1.69e+06,0,CDTR000000
338647,ZDFS000001,100000,0,BUEXP,PY1_ACTUAL,B,0,2.26e+05,0,CDEOWF0000
338648,ZDFS000001,100000,0,BUEXP,PY1_ACTUAL,B,0,3.38e+06,0,CDED000000
338649,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,1.02e+06,0,CDTREN0000
338650,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,1.40e+06,0,CDTRBD0000
338651,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,-4.96e+04,0,CDTR000000
338652,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,1.25e+06,0,CDEDWF0000
338653,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,3.47e+05,0,CDEDLI0000
338654,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,2.80e+04,0,CDEDCONP00
338655,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,0.00e+00,0,CDEDCO0000
338656,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,1.40e+05,0,CDEDCCNP00
338657,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,1.73e+06,0,CDEDCC0000
338658,ZDFS000001,100000,0,BUEXP,CY_REVBUD,B,0,1.20e+06,0,CDEDBD0000

In [11]:
df.describe()

                fund          data
count  338659.000000  3.386590e+05
mean   346678.754960  3.917305e+05
std    241952.676284  6.151873e+06
min    100000.000000 -5.014369e+08
25%    100000.000000  2.700000e+02
50%    217001.000000  4.787000e+03
75%    601000.000000  4.371300e+04
max    802000.000000  3.282377e+08

#### All except fund & data are categorical.

#### Here we can see clearly the most expensive line item is $802,000.00.

#### And the least expensive line item is $100,000.00.

#### But the mean average is much closer to the least expensive  $346678.75.

In [50]:
df.dtypes

org         object
fund         int64
program     object
object      object
col         object
mut         object
mud         object
data       float64
proj        object
grnt        object
dtype: object

#### fund is an int, data a float.

In [51]:
df.count()

org        338659
fund       338659
program    338659
object     338659
col        338659
mut        338659
mud        338659
data       338659
proj       338659
grnt       338659
dtype: int64

#### 338,659 rows

In [64]:
len(df.columns)

10

#### 10 columns

#### Now I select by column and string match for a particular organization code "ATAT000001"

In [66]:
ATAT000001 = df[df.org == "ATAT000001"]
ATAT000001

,org,fund,program,object,col,mut,mud,data,proj,grnt
0,ATAT000001,100000,0,524,V55_TOTAL,B,0,5.24e+03,0,LALS000000
1,ATAT000001,100000,0,651532,CY_REVBUD,B,0,1.49e+05,3MFTS2AT01,LALS000000
2,ATAT000001,100000,0,642233,PY1_ACTUAL,B,0,3.51e+05,7AT2WA0001,LALS000000
3,ATAT000001,100000,0,BUEXP,V55_TOTAL,B,AT_07,2.28e+05,3MFFA2AT01,LALS000000
4,ATAT000001,100000,0,521100,PY1_ACTUAL,B,0,2.76e+03,0,LALS000000
5,ATAT000001,100000,0,651602,CY_REVBUD,B,0,6.32e+04,3MFRM2AT01,LALS000000
6,ATAT000001,100000,0,EMS,V55_TOTAL,B,AT_05,7.50e+04,0,LALS000000
7,ATAT000001,100000,0,629011,PY1_ACTUAL,B,0,4.67e+05,7AT2PL0001,LALS000000
8,ATAT000001,100000,0,R,V55_TOTAL,B,0,4.84e+03,7AT2PK0001,LALS000000
9,ATAT000001,100000,0,6515,PY1_ACTUAL,B,0,3.55e+05,3MFTS2AT01,LALS000000
10,ATAT000001,100000,0,642,CY_REVBUD,B,0,2.40e+05,7AT2HC0001,LALS000000
11,ATAT000001,100000,0,65,V55_TOTAL,B,0,1.70e+05,3MFRM2AT01,LALS000000
12,ATAT000001,100000,0,6516,V55_TOTAL,B,0,1.70e+05,3MFRM2AT01,LALS000000
13,ATAT000001,100000,0,642233,CY_REVBUD,B,0,1.02e+06,7AT2ES0001,LALS000000
14,ATAT000001,100000,0,6422,V55_TOTAL,B,0,2.42e+05,7AT2HC0001,LALS000000
15,ATAT000001,100000,0,549000,V55_TOTAL,B,0,2.87e+04,0,LALS000000
16,ATAT000001,100000,0,542400,CY_REVBUD,B,0,4.11e+03,0,LALS000000
17,ATAT000001,701000,0,549,PY1_ACTUAL,B,0,-4.00e+00,0,LALS000000
18,ATAT000001,100000,0,BUEXP,PY1_ACTUAL,B,0,-1.00e+02,0,LAASCA0000
19,ATAT000001,100000,0,FTE_TOT,V55_TOTAL,B,AT_01,1.00e+00,0,LALS000000
20,ATAT000001,100000,0,651520,PY1_ACTUAL,B,0,1.55e+03,3MFTS2AT01,LALS000000
21,ATAT000001,100000,0,E,V55_TOTAL,B,AT_06,1.52e+05,0,LALS000000
22,ATAT000001,100000,0,487210,V55_TOTAL,B,AT_10,6.54e+04,0,LALS000000
23,ATAT000001,100000,0,651211,PY1_ACTUAL,B,0,1.64e+03,3MFPD2AT01,LALS000000
24,ATAT000001,100000,0,651512,CY_REVBUD,B,0,3.04e+04,3MFTS2AT01,LALS000000
25,ATAT000001,100000,0,651522,PY1_ACTUAL,B,0,8.30e+04,3MFTS2AT01,LALS000000
26,ATAT000001,100000,0,487210,V55_TOTAL,B,AT_04,0.00e+00,0,LALS000000
27,ATAT000001,100000,0,E,PY1_ACTUAL,B,0,-1.00e+02,0,LAASCA0000
28,ATAT000001,100000,0,48,V55_TOTAL,B,AT_05,7.50e+04,0,LALS000000
29,ATAT000001,100000,0,514540,V55_TOTAL,B,AT_01,5.20e+03,0,LALS000000
...,...,...,...,...,...,...,...,...,...,...
812,ATAT000001,100000,0,64,PY1_ACTUAL,B,0,2.62e+06,7AT2MF0001,LALS000000
813,ATAT000001,100000,0,514700,V55_TOTAL,B,AT_05,0.00e+00,0,LALS000000
814,ATAT000001,100000,0,487210,V55_TOTAL,B,AT_06,8.30e+04,0,LALS000000
815,ATAT000001,100000,0,514,PY1_ACTUAL,B,0,2.55e+06,0,LALS000000
816,ATAT000001,100000,0,43,V55_TOTAL,B,AT_03,0.00e+00,0,LALS000000
817,ATAT000001,100000,0,642233,PY1_ACTUAL,B,0,4.67e+05,7AT2PL0001,LALS000000
818,ATAT000001,100000,0,514100,V55_TOTAL,B,AT_06,1.61e+04,0,LALS000000
819,ATAT000001,100000,0,514510,CY_REVBUD,B,0,2.61e+05,0,LALS000000
820,ATAT000001,100000,0,64,CY_REVBUD,B,0,1.02e+06,7AT2ES0001,LALS000000
821,ATAT000001,100000,0,532,CY_REVBUD,B,0,1.43e+05,0,LALS000000
822,ATAT000001,100000,0,642,CY_REVBUD,B,0,5.01e+05,7AT2PL0001,LALS000000
823,ATAT000001,100000,0,511302,PY1_ACTUAL,B,0,9.02e+02,0,LALS000000
824,ATAT000001,100000,0,R,V55_TOTAL,B,AT_10,1.20e+05,0,LALS000000
825,ATAT000001,100000,0,524,PY1_ACTUAL,B,0,1.26e+03,0,LALS000000
826,ATAT000001,100000,0,532000,PY1_ACTUAL,B,0,3.37e+04,0,LALS000000
827,ATAT000001,100000,0,64,PY1_ACTUAL,B,0,2.24e+05,7AT2HC0001,LALS000000
828,ATAT000001,100000,0,651510,CY_REVBUD,B,0,1.14e+03,3MFTS2AT01,LALS000000
829,ATAT000001,100000,0,549,V55_TOTAL,B,0,2.87e+04,0,LALS000000
830,ATAT000001,100000,0,629,PY1_ACTUAL,B,0,2.24e+05,7AT2DR0001,LALS000000
831,ATAT000001,100000,0,549000,V55_TOTAL,B,AT_09,9.00e+04,0,LALS000000
832,ATAT000001,100000,0,651303,V55_TOTAL,B,0,3.41e+02,3MFFA2AT01,LALS000000
833,ATAT000001,100000,0,642,V55_TOTAL,B,0,1.03e+06,7AT2ES0001,LALS000000
834,ATAT000001,100000,0,542,CY_REVBUD,B,0,8.60e+03,0,LALS000000
835,ATAT000001,100000,0,6512,V55_TOTAL,B,0,5.90e+04,3MFPD2AT01,LALS000000
836,ATAT000001,100000,0,651201,V55_TOTAL,B,0,4.59e+03,3MFPD2AT01,LALS000000
837,ATAT000001,100000,0,R,V55_TOTAL,B,0,3.80e+05,7AT2WA0001,LALS000000
838,ATAT000001,100000,0,POS,V55_TOTAL,B,AT_01,1.00e+00,0,LALS000000
839,ATAT000001,100000,0,629,PY1_ACTUAL,B,0,4.48e+03,7AT2PK0001,LALS000000
840,ATAT000001,100000,0,IAREV,CY_REVBUD,B,0,1.02e+06,7AT2ES0001,LALS000000
841,ATAT000001,100000,0,6512,CY_REVBUD,B,0,7.89e+04,3MFPD2AT01,LALS000000

In [55]:
# e.g. 0.01
pd.set_option('display.precision', 2)

In [57]:
ATAT000001.describe()

            fund      data
count     842.00  8.42e+02
mean   108565.32  4.75e+05
std     71277.11  1.50e+06
min    100000.00 -5.17e+06
25%    100000.00  1.39e+03
50%    100000.00  7.50e+04
75%    100000.00  2.74e+05
max    701000.00  1.06e+07

#### Here we can see clearly the most expensive line item is $701,000.00.

#### And the least expensive line item is $100,000.00.

#### But the mean average is much closer to the least expensive  $108,565.32.